
services:
  gateway:
    build:
      context: ./gateway
    networks:
      - ehospital

  frontend:
    build:
      context: ./frontend
    networks:
      - ehospital

  backend:
    build:
      context: .
    networks:
      - ehospital

networks:
  ehospital:
    driver: bridge
